# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 13 Pro"
])

scheme("ScreenshotTests")
clear_previous_screenshots(true)